// ===== src/dev/hub-preview/HubPreview.tsx =====
'use client';

/**
 * Development-only harness for the signed-out-proof parts of the arcade shell.
 *
 * The real hub sits behind Supabase auth, which makes the menus impossible to
 * eyeball locally without a live project. This route mounts the same components
 * against fixed mock state so layout, spacing and states can be reviewed (and
 * screenshotted) without signing in. It is generated by
 * scripts/sync-dev-routes.js for `npm run dev` and removed before type-check,
 * lint and build, so it never ships.
 */

import { useMemo, useState } from 'react';
import { GameLibrary } from '@/components/arcade/GameLibrary';
import { ThemedGameCanvas } from '@/components/arcade/ThemedGameCanvas';
import { HubHeader, type ArcadeTab } from '@/components/arcade/HubHeader';
import { HubNotifications } from '@/components/arcade/HubNotifications';
import { SignInGate } from '@/components/arcade/HubGate';
import { StatTile } from '@/components/ui/StatTile';
import { ProgressBar } from '@/components/ui/ProgressBar';
import { Chip } from '@/components/ui/Chip';
import { AVAILABLE_GAMES } from '@/data/Games';
import type { GameModule, GameScore } from '@/lib/types';
import { CurrencyService } from '@/services/CurrencyService';
import { AchievementService } from '@/services/AchievementService';
import type { AudioManager } from '@/services/AudioManager';
import { PLAYABLE_GAME_CATALOG } from '@/lib/gameCatalog';
import { formatCoins } from '@/lib/utils';

type Scenario = 'fresh' | 'mid' | 'rich' | 'gate' | 'run';

/**
 * A stand-in GameModule so the run shell (title bar, HUD, ready/paused/ended
 * overlays) can be reviewed without loading a real game.
 */
function createStubGame(): GameModule {
  const score: GameScore = {
    score: 18_420,
    pickups: 24,
    timePlayedMs: 96_000,
    coinsEarned: 184,
  };
  let hue = 200;
  return {
    manifest: AVAILABLE_GAMES.find(game => game.id === 'space')!,
    init: () => {},
    update: () => {
      hue = (hue + 0.4) % 360;
    },
    render: ctx => {
      ctx.fillStyle = `hsl(${hue}, 45%, 12%)`;
      ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
      ctx.fillStyle = '#fff';
      ctx.font = '28px system-ui';
      ctx.textAlign = 'center';
      ctx.fillText('stub game surface', ctx.canvas.width / 2, ctx.canvas.height / 2);
    },
    destroy: () => {},
    getScore: () => score,
    isGameOver: () => false,
  };
}

interface ScenarioState {
  label: string;
  coins: number;
  unlockedTiers: number[];
  unlockedGames: string[];
}

const SCENARIOS: Record<'fresh' | 'mid' | 'rich', ScenarioState> = {
  fresh: {
    label: 'New player',
    coins: 320,
    unlockedTiers: [0],
    unlockedGames: ['runner'],
  },
  mid: {
    label: 'Mid progression',
    coins: 6400,
    unlockedTiers: [0, 1, 2],
    unlockedGames: ['runner', 'snake', 'breakout', 'puzzle', 'bubble', 'space'],
  },
  rich: {
    label: 'Deep progression',
    coins: 88_500,
    unlockedTiers: [0, 1, 2, 3],
    unlockedGames: PLAYABLE_GAME_CATALOG.map(game => game.id),
  },
};

const ACTIVITY = {
  runner: { plays: 12, lastPlayed: Date.now() - 3 * 86_400_000 },
  space: { plays: 3, lastPlayed: Date.now() - 2 * 3_600_000 },
};

export default function HubPreview() {
  const [scenario, setScenario] = useState<Scenario>('mid');
  const [activeTab, setActiveTab] = useState<ArcadeTab>('games');
  const [showToasts, setShowToasts] = useState(false);
  const stubGame = useMemo(createStubGame, []);
  const stubCurrency = useMemo(() => new CurrencyService(), []);
  const stubAchievements = useMemo(() => new AchievementService(), []);

  const state =
    scenario === 'gate' || scenario === 'run' ? SCENARIOS.mid : SCENARIOS[scenario];
  const unlockedCount = state.unlockedGames.length;
  const releasedTiers = Array.from(
    new Set(PLAYABLE_GAME_CATALOG.map(game => game.tier))
  );
  const openTiers = releasedTiers.filter(tier => state.unlockedTiers.includes(tier));

  return (
    <div className="relative min-h-screen bg-canvas px-4 pb-16 text-ink">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[420px] bg-[radial-gradient(80%_100%_at_50%_0%,rgba(124,107,255,0.14),transparent_70%)]"
      />

      <HubHeader
        activeTab={activeTab}
        onTabChange={setActiveTab}
        showTabs={scenario !== 'gate' && scenario !== 'run'}
        inGame={scenario === 'run'}
        onBackToHub={() => {}}
        signedIn={scenario !== 'gate'}
        authDisabled={false}
        playerName="PreviewPlayer"
        onOpenAuth={() => {}}
        onSignOut={() => {}}
        onOpenHelp={() => {}}
        onOpenAudio={() => {}}
      />

      {showToasts && (
        <HubNotifications
          notifications={[
            {
              id: '1',
              type: 'achievement',
              title: 'Coin Collector',
              message: '+250 coins',
              timestamp: new Date(),
            },
            {
              id: '2',
              type: 'levelup',
              title: 'Level 8',
              message: 'New perk unlocked',
              timestamp: new Date(),
            },
          ]}
          onDismiss={() => setShowToasts(false)}
        />
      )}

      <main className="mx-auto max-w-7xl space-y-6">
        <div className="flex flex-wrap items-center gap-2 rounded-panel border border-dashed border-line bg-surface p-3">
          <span className="mr-1 text-[11px] font-bold uppercase tracking-[0.12em] text-ink-faint">
            Preview state
          </span>
          {(Object.keys(SCENARIOS) as Array<keyof typeof SCENARIOS>).map(key => (
            <Chip
              key={key}
              selected={scenario === key}
              onClick={() => setScenario(key)}
            >
              {SCENARIOS[key].label}
            </Chip>
          ))}
          <Chip selected={scenario === 'gate'} onClick={() => setScenario('gate')}>
            Sign-in gate
          </Chip>
          <Chip selected={scenario === 'run'} onClick={() => setScenario('run')}>
            Run shell
          </Chip>
          <Chip selected={showToasts} onClick={() => setShowToasts(v => !v)}>
            Toasts
          </Chip>
        </div>

        {scenario === 'run' ? (
          <ThemedGameCanvas
            game={stubGame}
            currencyService={stubCurrency}
            audioManager={{} as unknown as AudioManager}
            achievementService={stubAchievements}
            onExit={() => setScenario('mid')}
          />
        ) : scenario === 'gate' ? (
          <SignInGate onOpenAuth={() => {}} />
        ) : (
          <>
            <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
              <StatTile
                label="Balance"
                value={formatCoins(state.coins)}
                suffix="coins"
                tone="coin"
                footer={
                  <div className="text-xs text-ink-faint">
                    Next tier unlock: 10,000 coins (Tier 3)
                  </div>
                }
              />
              <StatTile
                label="Games unlocked"
                value={unlockedCount}
                suffix={`/ ${PLAYABLE_GAME_CATALOG.length}`}
                footer={
                  <ProgressBar
                    value={unlockedCount}
                    max={PLAYABLE_GAME_CATALOG.length}
                    size="sm"
                    label="Games unlocked"
                  />
                }
              />
              <StatTile
                label="Tiers open"
                value={openTiers.length}
                suffix={`/ ${releasedTiers.length}`}
                footer={
                  <ProgressBar
                    value={openTiers.length}
                    max={releasedTiers.length}
                    size="sm"
                    label="Tiers unlocked"
                  />
                }
              />
              <StatTile
                label="Daily challenges"
                value={2}
                suffix="/ 3"
                footer={
                  <span className="text-xs font-semibold text-brand-bright">
                    View challenges
                  </span>
                }
              />
            </div>

            <GameLibrary
              games={AVAILABLE_GAMES}
              unlockedTiers={state.unlockedTiers}
              unlockedGames={state.unlockedGames}
              currentCoins={state.coins}
              activity={ACTIVITY}
              onGameSelect={() => {}}
              onTierUnlock={() => {}}
              onGameUnlock={() => {}}
            />
          </>
        )}
      </main>
    </div>
  );
}
